name: pr-test-run
on:
  pull_request:
    branches: [ main ]
jobs:
  run-gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          
      - name: Create `hibernate.properties`
        run: |
          mkdir -p src/main/resources
          echo "hibernate.connection.driver_class=org.h2.Driver" > src/main/resources/hibernate.properties
          echo "hibernate.connection.url=jdbc:h2:mem:testdb" >> src/main/resources/hibernate.properties
          echo "hibernate.connection.username=sa" >> src/main/resources/hibernate.properties
          echo "hibernate.connection.password=" >> src/main/resources/hibernate.properties
          echo "hibernate.dialect=org.hibernate.dialect.H2Dialect" >> src/main/resources/hibernate.properties
          echo "hibernate.hbm2ddl.auto=update" >> src/main/resources/hibernate.properties

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execution permission to ./gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle checks
        run: ./gradlew check --continue --dependency "com.h2database:h2:2.2.224"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/test-results/test/*

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/

      - name: Check for test failures
        if: failure()
        run: |
          echo "::error::Tests failed! Please review the test results and reports artifacts."
          exit 1
